### ISSUE TITLE
Error creating PR

### ISSUE THREAD

**Issue by yajo** [OCA/oca-port#20]
## Module
product_tax_multicompany_default

## Describe the bug
It won't create the PR.

## To Reproduce

Run:

    oca-port --repo-name multi-company --verbose --upstream upstream --fork origin 14.0 16.0 product_tax_multicompany_default

After I tell it to create a draft PR, I get this exception:

```
        Create a draft PR from 'oca-port-pr-464-from-14.0-to-16.0' to '16.0' against OCA/multi-company? [y/N]: y
Traceback (most recent call last):
  File "/nix/store/1v9vvq131m5ddpi37gsiicmpay2xmk57-python3.10-oca-port-0.12/bin/.oca-port-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/spcxakfs6hg2yrhbxp6c2gkk538q30w0-python3.10-click-8.1.3/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/nix/store/spcxakfs6hg2yrhbxp6c2gkk538q30w0-python3.10-click-8.1.3/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/nix/store/spcxakfs6hg2yrhbxp6c2gkk538q30w0-python3.10-click-8.1.3/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nix/store/spcxakfs6hg2yrhbxp6c2gkk538q30w0-python3.10-click-8.1.3/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/nix/store/1v9vvq131m5ddpi37gsiicmpay2xmk57-python3.10-oca-port-0.12/lib/python3.10/site-packages/oca_port/__init__.py", line 118, in main
    ).run()
  File "/nix/store/1v9vvq131m5ddpi37gsiicmpay2xmk57-python3.10-oca-port-0.12/lib/python3.10/site-packages/oca_port/port_addon_pr.py", line 94, in run
    self._port_pull_requests(branches_diff)
  File "/nix/store/1v9vvq131m5ddpi37gsiicmpay2xmk57-python3.10-oca-port-0.12/lib/python3.10/site-packages/oca_port/port_addon_pr.py", line 146, in _port_pull_requests
    self._create_pull_request(pr_branch, pr_data, processed_prs)
  File "/nix/store/1v9vvq131m5ddpi37gsiicmpay2xmk57-python3.10-oca-port-0.12/lib/python3.10/site-packages/oca_port/port_addon_pr.py", line 359, in _create_pull_request
    response = misc._request_github(
  File "/nix/store/1v9vvq131m5ddpi37gsiicmpay2xmk57-python3.10-oca-port-0.12/lib/python3.10/site-packages/oca_port/misc.py", line 386, in _request_github
    raise RuntimeError(response.text)
RuntimeError: {"message":"Validation Failed","errors":[{"resource":"PullRequest","field":"head","code":"invalid"}],"documentation_url":"https://docs.github.com/rest/reference/pulls#create-a-pull-request"}
```
**Expected behavior**
PR created.

**Additional context**
I'm trying to port https://github.com/OCA/multi-company/pull/464 to 16.0.

**Comment by sebalix** [comment]
I already seen this error in the past, and I think @simahawk spotted it too...
I made a try and ported your PR 464 successfully: https://github.com/OCA/multi-company/pull/478 (maybe not resolved the conflicts as expected that said, was not the purpose).

Are you using the "last" type of personal GH token that starts with `ghp_`?

**Comment by SirAionTech** [comment]
I am having this same error, here the stack

<details><summary>Details</summary>
<pre>
[...]
- Port PR #1048 (https://github.com/OCA/account-financial-reporting/pull/1048) [FIX] account_financial_report: Empty format...
	Port it? [y/N]: y
	Create branch oca-port-from-14.0-to-16.0-pr-1048 from origin/16.0...
		Apply 6eb8b6d3 [FIX] account_financial_report: Empty format...
	🎉 Last PR processed! 🎉
	Push branch 'oca-port-from-14.0-to-16.0-pr-1048' to remote 'SirAionTech'? [y/N]: y
	Create a draft PR from 'oca-port-from-14.0-to-16.0-pr-1048' to '16.0' against OCA/account-financial-reporting? [y/N]: y
Traceback (most recent call last):
  File "/path/to/.local/bin/oca-port", line 8, in <module>
    sys.exit(main())
  File "/path/to/.local/pipx/venvs/oca-port/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/path/to/.local/pipx/venvs/oca-port/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/path/to/.local/pipx/venvs/oca-port/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/path/to/.local/pipx/venvs/oca-port/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/path/to/.local/pipx/venvs/oca-port/lib/python3.10/site-packages/oca_port/cli/main.py", line 151, in main
    app.run()
  File "/path/to/.local/pipx/venvs/oca-port/lib/python3.10/site-packages/oca_port/app.py", line 167, in run
    output = self.run_port()
  File "/path/to/.local/pipx/venvs/oca-port/lib/python3.10/site-packages/oca_port/app.py", line 184, in run_port
    return PortAddonPullRequest(self).run()
  File "/path/to/.local/pipx/venvs/oca-port/lib/python3.10/site-packages/oca_port/port_addon_pr.py", line 90, in run
    self._port_pull_requests(branches_diff)
  File "/path/to/.local/pipx/venvs/oca-port/lib/python3.10/site-packages/oca_port/port_addon_pr.py", line 147, in _port_pull_requests
    self._create_pull_request(pr_branch, pr_data, processed_prs)
  File "/path/to/.local/pipx/venvs/oca-port/lib/python3.10/site-packages/oca_port/port_addon_pr.py", line 382, in _create_pull_request
    response = github.request(
  File "/path/to/.local/pipx/venvs/oca-port/lib/python3.10/site-packages/oca_port/utils/github.py", line 28, in request
    raise RuntimeError(response.text)
RuntimeError: {"message":"Not Found","documentation_url":"https://docs.github.com/rest/pulls/pulls#create-a-pull-request"}
</pre>
</details> 

reading the above comment reminds me that I did not supply a token, my bad, but maybe the error could point to that instead of raising a generic error?
