### ISSUE TITLE
Migration does not end

### ISSUE THREAD

**Issue by flachica** [OCA/oca-port#9]
## Describe the bug
When execute `oca-port 14.0 15.0 support_branding --verbose --fork flachica` the process throw an exception

```
support_branding already exists on 15.0-mig-support_branding, checking PRs to port...
Traceback (most recent call last):
  File "/home/fernando/proyectos/venv/bin/oca-port", line 8, in <module>
    sys.exit(main())
  File "/home/fernando/proyectos/venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/fernando/proyectos/venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/fernando/proyectos/venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/fernando/proyectos/venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/fernando/proyectos/venv/lib/python3.10/site-packages/oca_port/__init__.py", line 124, in main
    ).run()
  File "/home/fernando/proyectos/venv/lib/python3.10/site-packages/oca_port/migrate_addon.py", line 112, in run
    ).run()
  File "/home/fernando/proyectos/venv/lib/python3.10/site-packages/oca_port/port_addon_pr.py", line 82, in run
    branches_diff = BranchesDiff(
  File "/home/fernando/proyectos/venv/lib/python3.10/site-packages/oca_port/port_addon_pr.py", line 384, in __init__
    self.to_branch_all_commits, _ = self._get_branch_commits(self.to_branch.ref())
  File "/home/fernando/proyectos/venv/lib/python3.10/site-packages/oca_port/port_addon_pr.py", line 403, in _get_branch_commits
    com = misc.Commit(commit)
  File "/home/fernando/proyectos/venv/lib/python3.10/site-packages/oca_port/misc.py", line 103, in __init__
    self.files = {f for f in set(commit.stats.files.keys()) if "=>" not in f}
  File "/home/fernando/proyectos/venv/lib/python3.10/site-packages/git/objects/commit.py", line 315, in stats
    text = self.repo.git.diff(self.parents[0].hexsha, self.hexsha, '--', numstat=True)
  File "/home/fernando/proyectos/venv/lib/python3.10/site-packages/git/cmd.py", line 639, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/home/fernando/proyectos/venv/lib/python3.10/site-packages/git/cmd.py", line 1184, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/home/fernando/proyectos/venv/lib/python3.10/site-packages/git/cmd.py", line 984, in execute
    raise GitCommandError(redacted_command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git diff --numstat ee148f64363155aba155d80bd5b9b8b648a1aeeb 2d32a425841477c521aaf45df6f2fd4d95fdafca --
  stderr: 'fatal: bad object ee148f64363155aba155d80bd5b9b8b648a1aeeb'
```

## To Reproduce
**Affected versions**:
oca-port 0.9
python 3.10.4

1. cd to repo folder
2. execute `oca-port 14.0 15.0 support_branding --verbose --fork flachica`
3. Get exception

**Expected behavior**
The process end with text of [image](https://warehouse-camo.ingress.cmh1.psfhosted.org/de29d66776d1578072af831115cc306f468576fb/68747470733a2f2f757365722d696d616765732e67697468756275736572636f6e74656e742e636f6d2f353331353238352f3132393335353434322d66383633616466662d333363302d346339312d623063622d6236383832333132653334302e706e67)

**Additional context**
* repo proyect cloned with git-aggregator. Initially point to a target branch (with merges applied)
* After exception was launched the branch is `15.0-mig-support_branding` and the last commit is `[IMP] support_branding: black, isort, prettier`

**Comment by sebalix** [comment]
Thanks for the report, I will try to figure out what is the issue, the fact the current branch is a consolidated one doesn't matter as the new branch is created from `15.0` and work from there.

**Comment by sebalix** [comment]
@flachica can you tell me if `origin` targets the OCA repository? Otherwise you can test by changing it this way if the OCA remote is named `oca` for instance:
```sh
$ oca-port 14.0 15.0 support_branding --verbose --fork flachica --upstream oca
```

**Comment by flachica** [comment]
Yes, I have origin and oca remotes point to oca/web

```
flachica	git@github.com:flachica/web.git (fetch)
flachica	git@github.com:flachica/web.git (push)
oca	https://github.com/OCA/web.git (fetch)
oca	https://github.com/OCA/web.git (push)
origin	https://github.com/OCA/web.git (fetch)
origin	https://github.com/OCA/web.git (push)
```

If I add `--upstream oca` my problem is solved. Thank you very much

**Comment by sebalix** [comment]
I'm wondering why then it was not working with `origin` :thinking:

**Comment by flachica** [comment]
I think that the configuration of my repo.yaml is bad and git-aggregator does not include origin. I make a second check and oca-port does not raise Exception

Thanks a lot for yours work

**Comment by sebalix** [comment]
Ok, thanks for the feedback! I close the issue then, if it happens again feel free to re-open.
